### ISSUE TITLE
ArgumentOutOfRangeException 

### ISSUE THREAD

**Issue by darkfriend77** [MarkioE/SimpleNet#46]
Something strange happens here ... need help, I can reproduce the failure

fail: Networker.Client.ClientPacketProcessor[0]
      System.ArgumentOutOfRangeException: Index and count must refer to a location within the buffer.
      Parameter name: bytes
         at Networker.Client.ClientPacketProcessor.Process(Byte[] buffer, ISender sender) in C:\Users\admin\Source\Repos\Networker\Networker\Client\ClientPacketProcessor.cs:line 134
         at Networker.Client.ClientPacketProcessor.Process(Socket socket) in C:\Users\admin\Source\Repos\Networker\Networker\Client\ClientPacketProcessor.cs:line 70

**Comment by darkfriend77** [comment]
https://github.com/darkfriend77/SabberStoneNetwork/tree/01c819f641d21d5bafcc3c278c17e0fa04134d29

running the SabberStoneNetwork will reproduce the error ...

![image](https://user-images.githubusercontent.com/17710198/57111916-31a7ef00-6d3e-11e9-829a-4326d0529bf7.png)
